Map<String, List<String>> countriesWithCities = {
  "Russia": [
    "Abakan",
    "Adler",
    "Anapa",
    "Arkhangelsk",
    "Astrakhan",
    "Barnaul",
    "Belgorod",
    "Birobidzhan",
    "Blagoveshchensk",
    "Bryansk",
    "Chelyabinsk",
    "Cherepovets",
    "Chita",
    "Dzerzhinsk",
    "Grozny",
    "Irkutsk",
    "Ivanovo",
    "Izhevsk",
    "Kaliningrad",
    "Kaluga",
    "Kazan",
    "Kemerovo",
    "Khabarovsk",
    "Khanty-Mansiysk",
    "Kirov",
    "Kostroma",
    "Krasnodar",
    "Krasnoyarsk",
    "Kurgan",
    "Kursk",
    "Lipetsk",
    "Magadan",
    "Makhachkala",
    "Maykop",
    "Moscow",
    "Murmansk",
    "Nalchik",
    "Nizhnekamsk",
    "Nizhnevartovsk",
    "Nizhny Novgorod",
    "Novokuznetsk",
    "Novorossiysk",
    "Novosibirsk",
    "Omsk",
    "Orenburg",
    "Oryol",
    "Penza",
    "Perm",
    "Petropavlovsk-Kamchatsky",
    "Petrozavodsk",
    "Podolsk",
    "Rostov-on-Don",
    "Ryazan",
    "Samara",
    "Saransk",
    "Saratov",
    "Smolensk",
    "Sochi",
    "Stavropol",
    "Sterlitamak",
    "Surgut",
    "Syktyvkar",
    "Tambov",
    "Tver",
    "Tolyatti",
    "Tomsk",
    "Tuapse",
    "Tula",
    "Tyumen",
    "Ufa",
    "Ulan-Ude",
    "Ulyanovsk",
    "Vladikavkaz",
    "Vladimir",
    "Volgograd",
    "Vologda",
    "Voronezh",
    "Yakutsk",
    "Yaroslavl",
    "Yekaterinburg",
    "Yoshkar-Ola",
    "Yuzhno-Sakhalinsk",
    "Zelenograd",
    "Zheleznogorsk",
    "Zlatoust"
  ],
  "United States": [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming"
  ]
};
